version: '2'

services:
    db:
        restart: always
        image: postgres:9.5
        ports:
            - "5434:5432"
        volumes:
            - .pgdata:/var/lib/postgresql/data/
    web:
        restart: always
        build: ./server
        ports:
            - "4000:80"
        volumes:
            - ./server/tpfinalso:/usr/src/app/tpfinalso
        depends_on:
            - db
        
